-- AlterTable
ALTER TABLE "Article" ALTER COLUMN "quick_look" SET DATA TYPE TEXT,
ALTER COLUMN "description" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "ArticleMetadata" ALTER COLUMN "title" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Category" ALTER COLUMN "name" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Country" ALTER COLUMN "name" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Keyword" ALTER COLUMN "keyword" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Role" ALTER COLUMN "name" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Status" ALTER COLUMN "name" SET DATA TYPE TEXT,
ALTER COLUMN "timestamp" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "TimeData" ALTER COLUMN "date_created" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "date_updated" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "date_deleted" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "email" SET DATA TYPE TEXT,
ALTER COLUMN "name" SET DATA TYPE TEXT,
ALTER COLUMN "last_name" SET DATA TYPE TEXT,
ALTER COLUMN "author_name" SET DATA TYPE TEXT,
ALTER COLUMN "last_active_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Website" ALTER COLUMN "name" SET DATA TYPE TEXT,
ALTER COLUMN "url" SET DATA TYPE TEXT;
